
services:
  app:
    build: .
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: vishwa
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: spring
    ports:
      - "5433:5432"
    volumes:
      - postgres-s-data:/var/lib/postgresql/data

volumes:
  postgres-s-data: